spring:
  application:
    name: supersave-backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
